In [ ]:
#The problemis faced by the airline is to detemine theportion of demend of each itenary to accept so as to maximise the total revenue.

In [1]:
#Importing libraries

In [2]:
import numpy as np
import scipy as sp
import pandas as pd
import xlrd

In [3]:
capacity_name = "data_mining_capacity.csv"
fare_name = "data_mining_fare.csv"
demand_name = "data_mining_demand.csv"
mapping_name = "data_mining_maping.csv"
cap= pd.read_csv(capacity_name)
fare = pd.read_csv(fare_name)
dem = pd.read_csv(demand_name)
mapp = pd.read_csv(mapping_name)
print(mapp.head(10))
#cap= capacity.iloc[:,1:]
#demand = demand.iloc[:,1:]
#fare = fare.iloc[:,1:]
print(cap.head(10))
print(fare.head(10))
print(dem.head(10))
print(mapp.head(10))

                Itenary                  Flight
0   20**I******20020920  LX0015520020920BOMZRHY
1   20BEIBOMBRU20020920  LX0015520020920BOMZRHY
2   20INIBOMBRU20020920  LX0015520020920BOMZRHY
3   23**I******20020920  LX0016820020920ZRHNRTY
4   23CHIZRHNRT20020920  LX0016820020920ZRHNRTY
5   69**I******20020920  LX0006420020920ZRHMIAY
6   83**I******20020919  LX0009520020919GRUZRHY
7  129**I******20020920  LX0024720020920KHIDXBY
8  129**I******20020920  LX0024720020920DXBZRHY
9  167**I******20020920  LX0064720020920CDGZRHY
                   Flight  Capacity
0  LX0006420020920ZRHMIAC        23
1  LX0006420020920ZRHMIAF         6
2  LX0006420020920ZRHMIAY       120
3  LX0009520020919EZEGRUC        50
4  LX0009520020919EZEGRUF        12
5  LX0009520020919EZEGRUY       200
6  LX0009520020919GRUZRHC        23
7  LX0009520020919GRUZRHF         9
8  LX0009520020919GRUZRHY       158
9  LX0015520020920BOMZRHC        41
                Itenary    Fare
0   20**I******20020920  378.48
1   20BEIBOMBRU20020920  217.54
2   20INIBOMBRU20020920  539.42
3   23**I******20020920  682.10
4   23CHIZRHNRT20020920  682.10
5   69**I******20020920  185.40
6   83**I******20020919    0.00
7  129**I******20020920    0.00
8  167**I******20020920  283.89
9  245**I******20020919    0.00
                Itenary  Demand
0   20**I******20020920  0.0922
1   20BEIBOMBRU20020920  0.2844
2   20INIBOMBRU20020920  1.1751
3   23**I******20020920  0.0000
4   23CHIZRHNRT20020920  0.0000
5   69**I******20020920  0.0050
6   83**I******20020919  1.4909
7  129**I******20020920  0.0060
8  167**I******20020920  0.6249
9  245**I******20020919  0.0073
                Itenary                  Flight
0   20**I******20020920  LX0015520020920BOMZRHY
1   20BEIBOMBRU20020920  LX0015520020920BOMZRHY
2   20INIBOMBRU20020920  LX0015520020920BOMZRHY
3   23**I******20020920  LX0016820020920ZRHNRTY
4   23CHIZRHNRT20020920  LX0016820020920ZRHNRTY
5   69**I******20020920  LX0006420020920ZRHMIAY
6   83**I******20020919  LX0009520020919GRUZRHY
7  129**I******20020920  LX0024720020920KHIDXBY
8  129**I******20020920  LX0024720020920DXBZRHY
9  167**I******20020920  LX0064720020920CDGZRHY

In [4]:
cap.head(10)

                   Flight  Capacity
0  LX0006420020920ZRHMIAC        23
1  LX0006420020920ZRHMIAF         6
2  LX0006420020920ZRHMIAY       120
3  LX0009520020919EZEGRUC        50
4  LX0009520020919EZEGRUF        12
5  LX0009520020919EZEGRUY       200
6  LX0009520020919GRUZRHC        23
7  LX0009520020919GRUZRHF         9
8  LX0009520020919GRUZRHY       158
9  LX0015520020920BOMZRHC        41

In [5]:
dem.head(10)

                Itenary  Demand
0   20**I******20020920  0.0922
1   20BEIBOMBRU20020920  0.2844
2   20INIBOMBRU20020920  1.1751
3   23**I******20020920  0.0000
4   23CHIZRHNRT20020920  0.0000
5   69**I******20020920  0.0050
6   83**I******20020919  1.4909
7  129**I******20020920  0.0060
8  167**I******20020920  0.6249
9  245**I******20020919  0.0073

In [6]:
mapp.head(10)

                Itenary                  Flight
0   20**I******20020920  LX0015520020920BOMZRHY
1   20BEIBOMBRU20020920  LX0015520020920BOMZRHY
2   20INIBOMBRU20020920  LX0015520020920BOMZRHY
3   23**I******20020920  LX0016820020920ZRHNRTY
4   23CHIZRHNRT20020920  LX0016820020920ZRHNRTY
5   69**I******20020920  LX0006420020920ZRHMIAY
6   83**I******20020919  LX0009520020919GRUZRHY
7  129**I******20020920  LX0024720020920KHIDXBY
8  129**I******20020920  LX0024720020920DXBZRHY
9  167**I******20020920  LX0064720020920CDGZRHY

In [7]:
c = - fare["Fare"]
c.head(10)

0   -378.48
1   -217.54
2   -539.42
3   -682.10
4   -682.10
5   -185.40
6     -0.00
7     -0.00
8   -283.89
9     -0.00
Name: Fare, dtype: float64

In [8]:
b1 = dem["Demand"]
b1

0       0.0922
1       0.2844
2       1.1751
3       0.0000
4       0.0000
5       0.0050
6       1.4909
7       0.0060
8       0.6249
9       0.0073
10      0.0803
11      0.0000
12      3.4221
13      0.0000
14      0.0000
15      0.0000
16      3.6228
17      4.2390
18      0.0027
19      0.3737
20      0.8687
21      0.2036
22      0.1200
23      0.3747
24      2.1093
25      0.0000
26      0.2826
27      0.0353
28      0.9456
29      2.2755
         ...
7919    0.0038
7920    0.0033
7921    0.0042
7922    0.0190
7923    0.0357
7924    0.0323
7925    0.0222
7926    0.0179
7927    0.0013
7928    0.4165
7929    0.1400
7930    0.0039
7931    0.0276
7932    0.0009
7933    0.0015
7934    0.0008
7935    0.0050
7936    0.9474
7937    0.0011
7938    0.0939
7939    0.2328
7940    0.0192
7941    0.0067
7942    0.0201
7943    0.0061
7944    0.0041
7945    0.0217
7946    0.0013
7947    0.0018
7948    0.5093
Name: Demand, Length: 7949, dtype: float64

In [9]:
b2 = cap["Capacity"]
b2.head

<bound method NDFrame.head of 0      23
1       6
2     120
3      50
4      12
5     200
6      23
7       9
8     158
9      41
10     13
11    130
12     18
13      3
14     30
15     47
16     11
17    174
18     49
19     11
20    177
21     32
22     90
23      8
24     42
25      8
26     43
27      8
28     39
29      6
30     47
31     20
32     78
33     60
34     96
35     31
36     68
37     18
38     29
39     11
40    145
41     28
42    115
43      9
44     77
45     57
46     97
47     41
48     60
49     25
50     86
51     30
52    293
Name: Capacity, dtype: int64>

In [10]:
b = b1.append(b2)
b.head

<bound method NDFrame.head of 0       0.0922
1       0.2844
2       1.1751
3       0.0000
4       0.0000
5       0.0050
6       1.4909
7       0.0060
8       0.6249
9       0.0073
10      0.0803
11      0.0000
12      3.4221
13      0.0000
14      0.0000
15      0.0000
16      3.6228
17      4.2390
18      0.0027
19      0.3737
20      0.8687
21      0.2036
22      0.1200
23      0.3747
24      2.1093
25      0.0000
26      0.2826
27      0.0353
28      0.9456
29      2.2755
        ...
23      8.0000
24     42.0000
25      8.0000
26     43.0000
27      8.0000
28     39.0000
29      6.0000
30     47.0000
31     20.0000
32     78.0000
33     60.0000
34     96.0000
35     31.0000
36     68.0000
37     18.0000
38     29.0000
39     11.0000
40    145.0000
41     28.0000
42    115.0000
43      9.0000
44     77.0000
45     57.0000
46     97.0000
47     41.0000
48     60.0000
49     25.0000
50     86.0000
51     30.0000
52    293.0000
Length: 8002, dtype: float64>

In [11]:
a1 = np.eye(7949)
a1.shape

(7949, 7949)

In [12]:
#a2 = demand.Demand.values
#a2.shape

In [13]:
#dict_map={}
#for i in mapping.Flight.unique():
#    dict_map[i] = mapping[mapping.Flight == i]['Itenary'].tolist()
    
#dict_map

In [14]:
a2 = pd.DataFrame(index = cap.Flight, columns = dem.Itenary)
a2 = a2.fillna(0)
for i in range(len(a2.index)):
    temp_array = mapp[mapp.Flight == a2.index[i]]
    for j in range(len(temp_array["Itenary"])):
        col = a2.columns.get_loc(temp_array["Itenary"].iloc[j])
        a2.iloc[i, col] = 1
        
a2.head(10)

Itenary,20**I******20020920,20BEIBOMBRU20020920,20INIBOMBRU20020920,23**I******20020920,23CHIZRHNRT20020920,69**I******20020920,83**I******20020919,129**I******20020920,167**I******20020920,245**I******20020919,...,21201975**I******20020920,21201981**I******20020920,21201987**I******20020920,21201991**I******20020920,21201992**I******20020920,21202000**I******20020920,21202002**I******20020920,21202003**I******20020920,21202004**I******20020920,21202616**I******20020919
Flight,,,,,,,,,,,,,,,,,,,,,
LX0006420020920ZRHMIAC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0006420020920ZRHMIAF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0006420020920ZRHMIAY,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
LX0009520020919EZEGRUC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0009520020919EZEGRUF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0009520020919EZEGRUY,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0009520020919GRUZRHC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0009520020919GRUZRHF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LX0009520020919GRUZRHY,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
LX0015520020920BOMZRHC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
a1.shape

(7949, 7949)

In [16]:
a = a2.values
A = np.concatenate((a1, a), axis = 0)
A.shape

(8002, 7949)

In [17]:
A.shape, b.shape, c.shape

((8002, 7949), (8002,), (7949,))

In [18]:
from scipy.optimize import linprog

In [19]:
solution = linprog(c, A_ub= A, b_ub= b, options={'maxiter': 7000, "disp": True})

Optimization terminated successfully.
         Current function value: -495873.532390
         Iterations: 4143

In [20]:
solution.x

array([0.0922, 0.2844, 1.1751, ..., 0.    , 0.    , 0.    ])

In [21]:
x = np.array(solution.x)
print(x)

[0.0922 0.2844 1.1751 ... 0.     0.     0.    ]

In [22]:
OptAlloc = np.dot(A[7949:, ], x)

In [23]:
cap. head

<bound method NDFrame.head of                     Flight  Capacity
0   LX0006420020920ZRHMIAC        23
1   LX0006420020920ZRHMIAF         6
2   LX0006420020920ZRHMIAY       120
3   LX0009520020919EZEGRUC        50
4   LX0009520020919EZEGRUF        12
5   LX0009520020919EZEGRUY       200
6   LX0009520020919GRUZRHC        23
7   LX0009520020919GRUZRHF         9
8   LX0009520020919GRUZRHY       158
9   LX0015520020920BOMZRHC        41
10  LX0015520020920BOMZRHF        13
11  LX0015520020920BOMZRHY       130
12  LX0016820020920ZRHNRTC        18
13  LX0016820020920ZRHNRTF         3
14  LX0016820020920ZRHNRTY        30
15  LX0024720020920DXBZRHC        47
16  LX0024720020920DXBZRHF        11
17  LX0024720020920DXBZRHY       174
18  LX0024720020920KHIDXBC        49
19  LX0024720020920KHIDXBF        11
20  LX0024720020920KHIDXBY       177
21  LX0025720020920TLVZRHC        32
22  LX0025720020920TLVZRHY        90
23  LX0039820020920GCIZRHC         8
24  LX0039820020920GCIZRHY        42
25  LX0039820020920JERGCIC         8
26  LX0039820020920JERGCIY        43
27  LX0039820020920ZRHJERC         8
28  LX0039820020920ZRHJERY        39
29  LX0048520020920LCYBSLC         6
30  LX0048520020920LCYBSLY        47
31  LX0056220020920ZRHNCEC        20
32  LX0056220020920ZRHNCEY        78
33  LX0064720020920CDGZRHC        60
34  LX0064720020920CDGZRHY        96
35  LX0077120020920BRUZRHC        31
36  LX0077120020920BRUZRHY        68
37  LX0108120020920FRAZRHC        18
38  LX0108120020920FRAZRHY        29
39  LX0130520020920OSLZRHC        11
40  LX0130520020920OSLZRHY       145
41  LX0132620020920ZRHDMEC        28
42  LX0132620020920ZRHDMEY       115
43  LX0148620020920ZRHPRGC         9
44  LX0148620020920ZRHPRGY        77
45  LX0280520020920GVAZRHC        57
46  LX0280520020920GVAZRHY        97
47  LX0280720020920GVAZRHC        41
48  LX0280720020920GVAZRHY        60
49  LX0413020020920ZRHBUDC        25
50  LX0413020020920ZRHBUDY        86
51  LX0424220020920ZRHCMBC        30
52  LX0424220020920ZRHCMBY       293>

In [24]:
cap["Optimal"] = OptAlloc
for i in range(len(cap["Flight"])):
    if cap.iloc[i, 1] - cap.iloc[i, 2] < 1:
        print(cap.iloc[i,0])

LX0016820020920ZRHNRTY
LX0148620020920ZRHPRGC